BUILD INDEX FOR TABLE ${schema}NATION
;

BUILD INDEX FOR TABLE ${schema}REGION
;

BUILD INDEX FOR TABLE ${schema}PART
;

BUILD INDEX FOR TABLE ${schema}SUPPLIER
;

BUILD INDEX FOR TABLE ${schema}PARTSUPP
;

BUILD INDEX FOR TABLE ${schema}CUSTOMER
;

BUILD INDEX FOR TABLE ${schema}ORDERS
;

BUILD INDEX FOR TABLE ${schema}LINEITEM
;