BUILD INDEX FOR TABLE ${schema}NATION
;
BUILD INDEX FOR TABLE ${schema}REGION
;
BUILD INDEX FOR TABLE ${schema}PART
;
BUILD INDEX FOR TABLE ${schema}SUPPLIER
;
BUILD INDEX FOR TABLE ${schema}PARTSUPP
;
BUILD INDEX FOR TABLE ${schema}CUSTOMER
;
BUILD INDEX FOR TABLE ${schema}ORDERS
;
BUILD INDEX FOR TABLE ${schema}LINEITEM
;

TUNE TABLE ${schema}NATION
;
TUNE TABLE ${schema}REGION
;
TUNE TABLE ${schema}PART
;
TUNE TABLE ${schema}SUPPLIER
;
TUNE TABLE ${schema}PARTSUPP
;
TUNE TABLE ${schema}CUSTOMER
;
TUNE TABLE ${schema}ORDERS
;
TUNE TABLE ${schema}LINEITEM
;