CREATE BITMAP INDEX S_NATIONKEY_IDX ON ${schema}SUPPLIER (S_NATIONKEY)
;
CREATE BITMAP INDEX PS_SUPPKEY_IDX ON ${schema}PARTSUPP (PS_SUPPKEY)
;
CREATE BITMAP INDEX L_ORDERKEY_IDX ON ${schema}LINEITEM (L_ORDERKEY)
;
CREATE BITMAP INDEX L_PARTKEY_IDX ON ${schema}LINEITEM (L_PARTKEY)
;
CREATE BITMAP INDEX L_SHIPDATE_CLUIDX ON ${schema}LINEITEM (L_SHIPDATE)
;
CREATE BITMAP INDEX L_RECEIPTDATE_IDX ON ${schema}LINEITEM (L_RECEIPTDATE)
;
CREATE BITMAP INDEX L_SUPPKEY_IDX ON ${schema}LINEITEM (L_SUPPKEY)
;
CREATE BITMAP INDEX N_REGIONKEY_IDX ON ${schema}NATION (N_REGIONKEY)
;
CREATE BITMAP INDEX O_ORDERDATE_CLUIDX ON ${schema}ORDERS (O_ORDERDATE)
;
CREATE BITMAP INDEX O_CUSTKEY_IDX ON ${schema}ORDERS (O_CUSTKEY)
;
CREATE BITMAP INDEX C_NATIONKEY_IDX ON ${schema}CUSTOMER (C_NATIONKEY)
;
TUNE TABLE ${schema}NATION
;
TUNE TABLE ${schema}REGION
;
TUNE TABLE ${schema}PART
;
TUNE TABLE ${schema}SUPPLIER
;
TUNE TABLE ${schema}PARTSUPP
;
TUNE TABLE ${schema}CUSTOMER
;
TUNE TABLE ${schema}ORDERS
;
TUNE TABLE ${schema}LINEITEM
;
