ALTER TABLE ${schema}NATION
    ADD CONSTRAINT N_REGIONKEY_FK 
            FOREIGN KEY (N_REGIONKEY)
            REFERENCES ${schema}REGION(R_REGIONKEY)
            NOCHECK
;

ALTER TABLE ${schema}SUPPLIER
    ADD CONSTRAINT S_NATIONKEY_FK
            FOREIGN KEY (S_NATIONKEY)
            REFERENCES ${schema}NATION(N_NATIONKEY)
            NOCHECK
;

ALTER TABLE ${schema}PARTSUPP
    ADD CONSTRAINT PARTSUPP_PK
            PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY),
        CONSTRAINT PS_PARTKEY_FK
            FOREIGN KEY (PS_PARTKEY)
            REFERENCES ${schema}PART(P_PARTKEY)
            NOCHECK,
        CONSTRAINT PS_SUPPKEY_FK
            FOREIGN KEY (PS_SUPPKEY)
            REFERENCES ${schema}SUPPLIER(S_SUPPKEY)
            NOCHECK
;

ALTER TABLE ${schema}CUSTOMER
    ADD CONSTRAINT C_NATIONKEY_FK
            FOREIGN KEY (C_NATIONKEY)
            REFERENCES ${schema}NATION(N_NATIONKEY)
            NOCHECK
;

ALTER TABLE ${schema}ORDERS
    ADD CONSTRAINT O_CUSTKEY_FK
            FOREIGN KEY (O_CUSTKEY)
            REFERENCES ${schema}CUSTOMER(C_CUSTKEY)
            NOCHECK
;

ALTER TABLE ${schema}LINEITEM
    ADD CONSTRAINT LINEITEM_PK
            PRIMARY KEY (L_ORDERKEY, L_LINENUMBER),
        CONSTRAINT L_ORDERKEY_FK
            FOREIGN KEY (L_ORDERKEY)
            REFERENCES ${schema}ORDERS(O_ORDERKEY)
            NOCHECK,
        CONSTRAINT L_PARTKEY_FK
            FOREIGN KEY (L_PARTKEY)
            REFERENCES ${schema}PART(P_PARTKEY)
            NOCHECK,
        CONSTRAINT L_SUPPKEY_FK
            FOREIGN KEY (L_SUPPKEY)
            REFERENCES ${schema}SUPPLIER(S_SUPPKEY)
            NOCHECK
;