SELECT O_ORDERPRIORITY, COUNT(*) AS ORDER_COUNT FROM %PARALLEL ORDERS WHERE O_ORDERDATE >= '1995-06-01' AND O_ORDERDATE < dateadd (mm, 3, cast ('1995-06-01' as date)) AND EXISTS ( SELECT * FROM %PARALLEL LINEITEM WHERE L_ORDERKEY = O_ORDERKEY AND L_COMMITDATE < L_RECEIPTDATE) GROUP BY O_ORDERPRIORITY ORDER BY O_ORDERPRIORITY
;
