CREATE VIEW REVENUE0 (SUPPLIER_NO, TOTAL_REVENUE) AS SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE*(1-L_DISCOUNT)) FROM %PARALLEL LINEITEM WHERE L_SHIPDATE >= '1995-07-01' AND L_SHIPDATE < dateadd(mm, 3, cast ('1995-07-01' as date)) GROUP BY L_SUPPKEY
;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE FROM %PARALLEL SUPPLIER, REVENUE0 WHERE S_SUPPKEY = SUPPLIER_NO AND TOTAL_REVENUE = ( SELECT MAX(TOTAL_REVENUE) FROM %PARALLEL REVENUE0) ORDER BY S_SUPPKEY
;

DROP VIEW REVENUE0
;
