SELECT SUM(L_EXTENDEDPRICE)/7.0 AS AVG_YEARLY FROM %PARALLEL LINEITEM, PART WHERE P_PARTKEY = L_PARTKEY AND P_BRAND = 'Brand#31' AND P_CONTAINER = 'LG BAG' AND L_QUANTITY < ( SELECT 0.2 * AVG(L_QUANTITY) FROM %PARALLEL LINEITEM WHERE L_PARTKEY = P_PARTKEY)
;
